### ISSUE TITLE
cls_token_segment_id 参数错误

### ISSUE THREAD

**Issue by bingxin3chen** [shibing624/nerpy#5]
## 默认参数错误
https://github.com/shibing624/nerpy/blob/ea3a594178956165238cb3e0da67dd1322904cc9/nerpy/ner_utils.py#L281
## 具体描述：
徐老师，这里应该是您写错了吧。cls_token_segment_id 应该为 0 才对。
![image](https://user-images.githubusercontent.com/89672905/229267665-e01cbaef-a8bb-4abd-91e2-f62927891c3a.png)

**Comment by shibing624** [comment]
yes, fixed.
