### ISSUE TITLE
用training_ner_model_zh_demo.py跑cner，eval的acc、f1都=0

### ISSUE THREAD

**Issue by beiTiaoLongJie** [shibing624/nerpy#7]
![image](https://github.com/shibing624/nerpy/assets/32008840/633cfdad-b01f-43ed-bbd2-da81d2f45752)

如标题，而且看起来不像是eval部分代码有问题，do_predict出来的结果也不对劲
![image](https://github.com/shibing624/nerpy/assets/32008840/8b5feafa-7cc4-4a97-ae1d-8b6f6fa77802)

请问有啥需要注意的吗？

**Comment by shibing624** [comment]
什么数据，示例数训练的吗？

**Comment by beiTiaoLongJie** [comment]
这两个文件有做改动，然后预训练模型是放在如上图所示的。


卡介仑caption
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shibing624/nerpy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月6日(星期二) 下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shibing624/nerpy] 用training_ner_model_zh_demo.py跑cner，eval的acc、f1都=0 (Issue #7)





 
什么数据，示例数训练的吗？

**Comment by beiTiaoLongJie** [comment]
> 什么数据，示例数训练的吗？

就是里面给的cner数据集，我把我改的两个文件发到你邮箱了，麻烦看看，谢谢！
